name: Cambia immagine

on:
  schedule:
    - cron: '0 * * * *'  # ogni ora
  workflow_dispatch:     # esecuzione manuale

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Scegli immagine
        run: |
          HOUR=$(date +'%H')
          if [ $HOUR -ge 9 -a $HOUR -lt 12 ] || [ $HOUR -ge 14 -a $HOUR -lt 17 ]; then
            cp Verde.png Immagine.png
          else
            cp Rosso.png Immagine.png
          fi

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Immagine.png
          git commit -m "Update immagine alle $(date)"
          git push
