name: Cambia immagine

on:
  schedule:
    - cron: '0 * * * *'   # ogni ora
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scegli immagine in base all'orario italiano
        run: |
          # otteniamo l'ora locale italiana usando Europe/Rome
          HOUR=$(TZ="Europe/Rome" date +'%H')

          echo "Ora italiana: $HOUR"

          if ([ $HOUR -ge 9 ] && [ $HOUR -lt 12 ]) || ([ $HOUR -ge 14 ] && [ $HOUR -lt 17 ]); then
            cp Verde.png Immagine.png
            echo "Uso Verde.png"
          else
            cp Rosso.png Immagine.png
            echo "Uso Rosso.png"
          fi

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Immagine.png
          git diff --quiet --cached || git commit -m "Aggiornata immagine alle $(TZ="Europe/Rome" date '+%H:%M')"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
